version: "3.3"

services:
  api:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend:/app/node_modules
  client:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend:/app/node_modules

volumes:
  frontend:
  backend:
