version: "3.3"

services:
  api:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
  client:
    build: ./frontend
    ports:
      - "80:80"

volumes:
  backend_node_modules:
